### ISSUE TITLE
Allow multiple load_paths in safe mode

### ISSUE THREAD

**Issue by nbergseng** [jekyll/jekyll-sass-converter#44]
load_paths work great in development, but since gh_pages builds in safe mode they won't work there.  Is there a problem with removing the check from sass_load_paths?

**Comment by parkr** [comment]
> Is there a problem with removing the check from sass_load_paths?

`safe` mode cannot allow custom load paths due to the security mandate of `safe` mode.

**Comment by nbergseng** [comment]
Any other way forward on multiple load_paths then? It'd be nice to be able to use vendor styles without having to prebuild or copy everything.

**Comment by parkr** [comment]
> Any other way forward on multiple load_paths then? It'd be nice to be able to use vendor styles without having to prebuild or copy everything.

The reason multiple load paths are shut off in safe mode is because of a fundamental inability to trust non-user content. Please write support@github.com if you would like to see this changed – safe mode is written for hosted versions of Jekyll. Maybe we can work with them to whitelist a few common libraries, like bourbon, compass, etc.

**Comment by lapidus** [comment]
+1
